# NOTE:
# the segment routing script below is mostly generated by LLM
# and its closely tied to modules/nixos/ranet.nix implementation
# BE VERY CAREFUL if you are trying to reuse any of this

{ lib
, formats
, writeShellScriptBin
, writeText
, iproute2
, gnugrep
, gawk
, coreutils
, nftables
}:

let
  bp = lib.blueprint;

  # nodes with a gravity /60 publish srv6 sids in the "6" nibble subspace (modules/nixos/ranet.nix)
  #   <base>6::2 End, transit waypoint, every server
  #   <base>6::3 End.DT46 into the egress vrf with snat to the node ipam address, bgp exits only
  srv6Nodes = lib.filter (h: lib.hasSuffix "0::/60" h.ranet.gravity.prefix)
    (lib.collect (h: h ? ranet && h.ranet ? gravity) bp.hosts);
  sidStem = h: "${lib.removeSuffix "0::/60" h.ranet.gravity.prefix}6";
  transitNodes = lib.filter (h: h.type == "server") srv6Nodes;
  exitNodes = lib.filter (h: h.type == "server" && lib.elem "router" h.tags) srv6Nodes;
  names = lib.concatMapStringsSep " " (h: h.hostName);
  cases = sid: lib.concatMapStringsSep "\n" (h: "        ${h.hostName}) echo ${sidStem h}::${sid} ;;");

  # replies to node local srv6 flows arrive ct invalid, seg6 output discards the unconfirmed
  # conntrack entry, and the nixos-fw input chain drops them before any other chain runs
  # remember the tuples this node sends into the mesh and accept exactly their replies
  # conntrack picks the flow up from the first accepted reply, so the entries can be short lived
  replyRules = writeText "gv-reply.nft" ''
    table inet nixos-fw {
      set gv4 {
        type ipv4_addr . inet_proto . inet_service . inet_service
        flags dynamic,timeout
        timeout 5m
      }
      set gv6 {
        type ipv6_addr . inet_proto . inet_service . inet_service
        flags dynamic,timeout
        timeout 5m
      }
      chain gv-output {
        type filter hook output priority filter; policy accept;
        oifname "gravity" meta l4proto { tcp, udp } update @gv4 { ip daddr . meta l4proto . th dport . th sport }
        oifname "gravity" meta l4proto { tcp, udp } update @gv6 { ip6 daddr . meta l4proto . th dport . th sport }
      }
    }
  '';

  # routes all traffic (v4+v6) thru mesh sourced from THIS node's announced ip
  # discovered at runtime from dummy0 (excluding the anycast ips)
  # exiting at babel selected node, or with --to at a named bgp exit using that node's ip,
  # optionally via --transit waypoints (srv6 segment list, node names from lib.blueprint)
  vpn = writeShellScriptBin "gv" ''
        set -u

        export PATH=${lib.makeBinPath [ iproute2 gnugrep gawk coreutils nftables ]}
        port=${toString bp.ranet.port}

        anycast4=23.161.104.17
        anycast6=2602:f590::23:161:104:17

        dev=dummy0
        state=/run/gv

        t=210
        v4=$(ip -4 -o addr show dev "$dev" scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | grep -vxF "$anycast4" | head -1)
        v6=$(ip -6 -o addr show dev "$dev" scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | grep -vxF "$anycast6" | head -1)

        transit_sid() {
          case "$1" in
    ${cases "2" transitNodes}
            *) echo "gv: no transit sid for '$1' (servers: ${names transitNodes})" >&2; return 1 ;;
          esac
        }

        exit_sid() {
          case "$1" in
    ${cases "3" exitNodes}
            *) echo "gv: no exit sid for '$1' (bgp exits: ${names exitNodes})" >&2; return 1 ;;
          esac
        }

        reply_accept_on() {
          nft list table inet nixos-fw >/dev/null 2>&1 || { echo "gv: no inet nixos-fw table, replies are not filtered" >&2; return 0; }
          nft -f ${replyRules}
          nft insert rule inet nixos-fw input iifname "gravity" ip saddr . meta l4proto . th sport . th dport @gv4 accept comment '"gv-reply"'
          nft insert rule inet nixos-fw input iifname "gravity" ip6 saddr . meta l4proto . th sport . th dport @gv6 accept comment '"gv-reply"'
          nft insert rule inet nixos-fw input iifname "gravity" icmp type { echo-reply, destination-unreachable, time-exceeded } accept comment '"gv-reply"'
          nft insert rule inet nixos-fw input iifname "gravity" icmpv6 type { destination-unreachable, packet-too-big, time-exceeded } accept comment '"gv-reply"'
        }

        reply_accept_off() {
          nft list table inet nixos-fw >/dev/null 2>&1 || return 0
          for h in $(nft -a list chain inet nixos-fw input | grep '"gv-reply"' | grep -oE 'handle [0-9]+' | awk '{print $2}'); do
            nft delete rule inet nixos-fw input handle "$h"
          done
          nft delete chain inet nixos-fw gv-output 2>/dev/null || true
          nft delete set inet nixos-fw gv4 2>/dev/null || true
          nft delete set inet nixos-fw gv6 2>/dev/null || true
        }

        clear() {
          for f in -4 -6; do
            for p in 148 149 5290 5299 5300; do ip $f rule del pref "$p" 2>/dev/null || true; done
            ip $f route flush table "$t" 2>/dev/null || true
          done
          reply_accept_off
          if [ -e "$state/tunsrc" ]; then ip sr tunsrc set ::; rm -f "$state/tunsrc"; fi
          rm -f "$state/mode"
        }

        case "''${1:-}" in
          on)
            shift
            transit=""; exit=""
            while [ $# -gt 0 ]; do
              case "$1" in
                --transit) [ $# -ge 2 ] || { echo "gv: --transit needs a node list" >&2; exit 1; }; transit="$2"; shift 2 ;;
                --to) [ $# -ge 2 ] || { echo "gv: --to needs a node" >&2; exit 1; }; exit="$2"; shift 2 ;;
                *) echo "usage: sudo gv on [--transit node,node,...] [--to exit]" >&2; exit 1 ;;
              esac
            done
            [ -n "$transit" ] && [ -z "$exit" ] && { echo "gv: --transit needs --to" >&2; exit 1; }
            segs=""
            if [ -n "$exit" ]; then
              for n in ''${transit//,/ }; do s=$(transit_sid "$n") || exit 1; segs="$segs$s,"; done
              s=$(exit_sid "$exit") || exit 1
              segs="$segs$s"
            fi
            [ -n "$v4$v6" ] || { echo "gv: no mesh source on $dev (is the gravity mesh up?)" >&2; exit 1; }
            clear
            mkdir -p "$state"
            ip -4 rule add pref 5290 ipproto udp dport "$port" lookup main
            ip -6 rule add pref 5290 ipproto udp dport "$port" lookup main
            if [ -z "$segs" ]; then
              [ -n "$v4" ] && ip -4 route replace default dev gravity src "$v4" table "$t"
              [ -n "$v6" ] && ip -6 route replace default dev gravity src "$v6" table "$t"
              echo native > "$state/mode"
            else
              # v4 inside srv6 has no outer source to inherit, and the exit sids only admit our own /60s
              src6=$(ip -6 -o addr show dev gravity scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1)
              [ -n "$src6" ] || { echo "gv: no global address on gravity for the outer source" >&2; clear; exit 1; }
              if [ "$(ip sr tunsrc show | awk '{print $3}')" = "::" ]; then ip sr tunsrc set "$src6"; touch "$state/tunsrc"; fi
              # the kernel subtracts the ipv6 and srh headroom from the route mtu itself
              mtu=$(ip -o link show type xfrm 2>/dev/null | grep -oE 'mtu [0-9]+' | head -1 | awk '{print $2}')
              mtu=''${mtu:-1400}
              [ -n "$v4" ] && ip -4 route replace default encap seg6 mode encap segs "$segs" dev gravity src "$v4" mtu "$mtu" table "$t"
              [ -n "$v6" ] && ip -6 route replace default encap seg6 mode encap segs "$segs" dev gravity src "$v6" mtu "$mtu" table "$t"
              # pref 150 (from <ipam> lookup 200) captures the source bound second lookup of every connect
              # and would bypass table t, so consult table t first and keep mesh internal prefixes on babel
              [ -n "$v4" ] && { ip -4 rule add pref 148 from "$v4" lookup 200 suppress_prefixlength 0; ip -4 rule add pref 149 from "$v4" lookup "$t"; }
              [ -n "$v6" ] && { ip -6 rule add pref 148 from "$v6" lookup 200 suppress_prefixlength 0; ip -6 rule add pref 149 from "$v6" lookup "$t"; }
              reply_accept_on
              echo "srv6 ''${transit:+transit=$transit }exit=$exit segs=$segs" > "$state/mode"
            fi
            ip -4 rule add pref 5299 lookup main suppress_prefixlength 0
            ip -6 rule add pref 5299 lookup main suppress_prefixlength 0
            ip -4 rule add pref 5300 lookup "$t"
            ip -6 rule add pref 5300 lookup "$t"
            echo "gv ON: v4+v6 -> gravity mesh (src ''${v4:-none} / ''${v6:-none}, $(cat "$state/mode"))"
            ;;
          off)
            clear
            echo "gv OFF: -> direct"
            ;;
          status)
            if ip -4 rule | grep -q '5300:'; then echo "gv: ON $(cat "$state/mode" 2>/dev/null || echo mode-unknown) (src ''${v4:-none} / ''${v6:-none})"; else echo "gv: OFF"; fi
            ;;
          *)
            echo "usage: sudo gv {on [--transit node,node,...] [--to exit]|off|status}"; exit 1 ;;
        esac
  '';

  registry = {
    public_key = lib.trim bp.ranet.publicKey;
    organization = bp.ranet.organization;

    nodes = lib.map
      (h: {
        common_name = h.hostName;
        endpoints = h.ranet.endpoints;
        remarks = {
          prefix = h.ranet.gravity.prefix or null;
          region = with h.meta; "${city}, ${country}";
          provider = h.providerName;
          extensions =
            let
              base = lib.removeSuffix "0::/60" (h.ranet.gravity.prefix or "");
              hasPrefix = h ? ranet && h.ranet ? gravity && lib.hasSuffix "0::/60" h.ranet.gravity.prefix;
            in
            # server only
              # segment routing SIDs at the "6" nibble subspace
              # ::1 = End.DT46 (exit here)
              # ::2 = End (transit waypoint)
            lib.optional (hasPrefix && h.type == "server") {
              type = "srv6";
              enabled = true;
              addresses = [ "${base}6::1" "${base}6::2" ];
            };
        };
      })
      (lib.collect
        (h: h ? ranet && h.ranet ? endpoints && (lib.length h.ranet.endpoints) > 0)
        bp.hosts);
  };
in
((formats.json { }).generate "gravity.json" registry).overrideAttrs {
  passthru = { inherit registry vpn; full = ./secrets.yaml; };
}
