systems = ["x86_64-linux", "aarch64-linux", "aarch64-darwin"]

include = [
  "legacyPackages.*.*",
  "legacyPackages.*.ocamlPackages.*",
  "devShells.*.default",
  "nixosConfigurations.*",
  "darwinConfigurations.*",
]

exclude = [
  "legacyPackages.*.gravity",                       # registry
  "legacyPackages.*.jitsi-meet",                    # insecure
  "legacyPackages.*.spotify",                       # unfree
  "legacyPackages.*.verus",                         # unused
  "legacyPackages.*.ripe-atlas-probe-measurements", # weird
  "legacyPackages.*.ripe-atlas-software-probe",     # weird
]
