substituters = ["https://cache.ysun.co"]

systems = ["x86_64-linux", "aarch64-linux", "aarch64-darwin"]

include = [
  "legacyPackages.*.*",
  "legacyPackages.*.ocamlPackages.*",
  "devShells.*.default",
  "nixosConfigurations.*",
  "darwinConfigurations.*",
]

exclude = [
  "legacyPackages.aarch64-darwin.bird3",       # unsupported
  "legacyPackages.aarch64-darwin.nirimon",     # unsupported
  "legacyPackages.aarch64-linux.mac-app-util", # unsupported
  "legacyPackages.x86_64-linux.mac-app-util",  # unsupported

  "legacyPackages.*.gravity",                       # registry
  "legacyPackages.*.jitsi-meet",                    # insecure
  "legacyPackages.*.ripe-atlas-probe-measurements", # weird
  "legacyPackages.*.ripe-atlas-software-probe",     # weird
  "legacyPackages.*.spotify",                       # unfree
  "legacyPackages.*.verus",                         # unused
]
